import { test, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { ShopContext } from "../context/ShopContext"; // Ensure path is correct
import "@testing-library/jest-dom/vitest";
import LatestCollection from "./LatestCollection";

test("renders latest collections title", () => {
  // 1. Create mock products so the .map() and .slice() don't fail
  const mockProducts = Array.from({ length: 5 }, (_, i) => ({
    _id: `prod${i}`,
    name: `Product ${i}`,
    price: 100,
    image: ["test-img.jpg"]
  }));

  const mockContextValue = {
    products: mockProducts
  };

  // 2. Wrap in both Router (for ProductItem Links) and Provider
  render(
    <MemoryRouter>
      <ShopContext.Provider value={mockContextValue}>
        <LatestCollection />
      </ShopContext.Provider>
    </MemoryRouter>
  );

  // 3. Assertions
  // Looking for the title text generated by the Title component
  const titlePart1 = screen.getByText(/LATEST/i);
  const titlePart2 = screen.getByText(/COLLECTIONS/i);
  
  expect(titlePart1).toBeInTheDocument();
  expect(titlePart2).toBeInTheDocument();

  // Verify that at least one product item rendered
  expect(screen.getByText(/Product 0/i)).toBeInTheDocument();
});